### ISSUE TITLE
[OSPO Book] GH Actions Bug:No such file or directory

### ISSUE THREAD

**Issue by anajsana** [todogroup/ospology#308]
@koozz just noticed that when merged your PR: https://github.com/todogroup/ospology/pull/306 GitHub actions drops the following error when trying to generate the pdf 🤔:

```pandoc: ospo-book/chapters/*.md: openBinaryFile: does not exist (No such file or directory)```

**Comment by koozz** [comment]
You can assign it to me, I will have a look.

**Comment by koozz** [comment]
I tried fixing this with the suggested pandoc docker image, but ran into an error.

I also tried to run it [as it previously was](https://github.com/todogroup/ospology/blob/cbca7ed30ad73300561b40693ea77b0f46ccfdc1/ospo-book/.github/workflows/build-pdf.yml), though I did need to install the package `texlive-latex-base` too.

Ended up with the same error as with the pandoc-docker image attempt:

```
Error producing PDF.
! LaTeX Error: File `titlesec.sty' not found.
```

Has this latex file worked before? Was another add-on or file added locally?

**Comment by thisisobate** [comment]
@anajsana @koozz it looks like wildcard substitution does not work inside GitHub Actions yaml files **args** fields.

> Remember that wildcard substitution (say, pandoc *.md) or other shell features frequently used with pandoc do not work inside GitHub Actions yaml files args: fields. Only [GitHub Actions context and expression syntax](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions) can be used here.

Take a look at [this pandoc example doc](https://github.com/pandoc/pandoc-action-example)

**Comment by koozz** [comment]
I tried that too, not the most fancy way, but then I run into the error that `titlesec.sty` cannot be found.

My current draft is now:

```yaml
name: Build PDF
on:
  push:
    branches:
      - main
    paths:
      - 'ospo-book/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ospo-book/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Gather input
      id: gather
      run: echo "files=$(ls ospo-book/chapters/*.md | xargs)" >> $GITHUB_OUTPUT
    - name: Generate book
      uses: docker://pandoc/core:3.1
      with:
        args: -N -s --template=ospo-book/docs/template.latex --output ospo-book/docs/output.pdf ${{ steps.gather.outputs.files }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: book-pdf
        path: ospo-book/docs/output.pdf
```
